version: '3.4'
services:
  app:
    build: .
    ports:
      - 8080:8080
    command: "/binn"
    environment:
      - TZ=Asia/Tokyo
      - AUTH_KEY=auth_key
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7.0.12
    ports:
      - 6380:6379
